### ISSUE TITLE
Unsafe unwrap could cause an application to panic  

### ISSUE THREAD

**Issue by kevin-valerio** [multiformats/rust-multihash#282] opened 2023-03-27 09:55 UTC
https://github.com/multiformats/rust-multihash/blob/8e14b1919bb0f60daa63f0b070278a2963603790/src/multihash.rs#L368

The `unwrap()` here might cause some crash using the library if an error occurred. For chains using Substrate, this could cause critical severity issues if an attacker is able to craft a malicious payload in order to trigger the unwrap. 

You can find an image of a malicious payload that will cause a panic below.
![image](https://user-images.githubusercontent.com/24193167/227899155-bbe9ce57-1dc1-4f95-b8d5-a2e9cbeaee32.png)

Below is an example of a fix that could be used : 

```rust
   if decode::is_last(b[i]) {
      match decode::u64(&b[..=i]) {
        Ok(val) => return Ok(val.0),
        Err(_) => return Err(Error::VarIntDecodeError),
      }
    }
```

**Comment by vmx** [comment] 2023-03-27 10:33
Your example malicious payload has 11 elements, but the we decode only up to 10 elements, due to the buffer having a length of 10. Do you have an example that leads to a panic?

Though, even if a panic cannot be triggered, it might still make sense to change the code for clarity.

**Comment by vmx** [comment] 2023-03-27 13:47
I've tried:

```rust
    #[test]
    fn decode_overflow() {
        let data = [203, 155, 0, 0, 0, 5, 67];
        let result = read_u64(&data[..]);
        println!("result: {:?}", result);
    }
```

Just as your error message, it returns an error that it's not minimal, but it does not panic. What am I missing?

**Comment by kevin-valerio** [comment] 2023-03-27 14:31
> 

Put in your Cargo.toml

```
[dependencies]

multihash = { version = "0.18.0", git="https://github.com/multiformats/rust-multihash", default-features = false, features = [ "multihash-impl", "sha2"] }
```

Because this function will have a different behaviour if you have `std` in the features (because of `#[cfg(not(feature = "std"))]`), so ensure std is not on the features

**Comment by mattheworris** [comment] 2023-04-11 17:58
We have also run into panics on this line with a NotMinimal encoding error. We are also using a Substrate, no-std environment. 
Any chance this fix will get merged in the near future?

**Comment by vmx** [comment] 2023-04-12 13:32
> We have also run into panics on this line with a NotMinimal encoding error.

That is an error and not a panic, isn't it?

I cannot reproduce the panic. If you can reproduce the panic, please provide a unit test for it.

**Comment by mattheworris** [comment] 2023-04-12 14:01
The NotMinimal error triggers a panic when it hits unwrap().

I tried to create a unit test, but I cannot get the unit tests to run
“no-std”. If features=std, then it doesn’t panic.

However, we cannot use “std” for Substrate.

Our unit tests will fail every time in a no-std environment.

**Comment by vmx** [comment] 2023-04-12 14:25
> The NotMinimal error triggers a panic when it hits unwrap().

Oh sorry, it took me a long time to understand all that. So the problem is that you have a non-minimal encoded varint. That varint is then decoded and returns a `NotMinimal` error. As we call `unwrap()`, it leads to a panic.

Let me try if I create a unit test triggering that, now that I've understood the issue.

**Comment by vmx** [comment] 2023-04-12 15:32
Alright, I now know why I wasn't able to reproduce it. The tests have `std` enabled (even with `--no-default-features`), hence it wasn't triggering the code path that contains the issue. On current master `--no-default-features` works as expected.

**Comment by vmx** [comment] 2023-04-12 16:29
I've created pull requests for

 - master: https://github.com/multiformats/rust-multihash/pull/291
 - 0.18: https://github.com/multiformats/rust-multihash/pull/292

**Closed** 2023-04-14 16:35 UTC

**Comment by mattheworris** [comment] 2023-04-14 17:10
Awesome, thanks!
