### ISSUE TITLE
Remove the APIs for hashing and only do the encoding

### ISSUE THREAD

**Issue by seamlik** [multiformats/rust-multihash#32] opened 2019-01-27 12:54 UTC
While I support #25 and #26 ,  wouldn't it be cleaner if this crate only handles Multihash itself and leaves the hashing logic to other crates? There are so many crates out there that can do hashing of all sorts, and one wouldn't want to include 2+ crates in the dependency graph for only one algorithm.

Right now this crate depends on other crates for SHA-1/2/3. Since the specification might even support an infinite number of hashing algorithms (I'm exaggerating), it is not ideal to let this crate depend on all of them.

**Comment by bochaco** [comment] 2019-06-05 20:03
I just try to start using this crate and was having issues when decoding a CID, and I just figured the problem is exactly that the multihash is hashing my sting rather than just prefixing it with hash-code and length, which I thought is what multihash specs defines, at least that's what I understood and saw happening with other implementations like JS that I've been using before, and I looked at Go impl which does the same, i.e. only encoding and no hashing.

**Comment by dignifiedquire** [comment] 2019-06-20 13:07
I think you are right, having the hashing functions in here makes life much harder than necessary. I think having the following in this crate makes more sense

```rust
/// Owned hash.
pub struct Multihash(Hash, Vec<u8>);

/// Referenced version, more similar to what we have currently
pub struct MultihashRef<'a>(Hash, &'a [u8]);
```
Wi

**Comment by dignifiedquire** [comment] 2019-06-20 14:23
Thinking about it some more, most of the code in #30 is good, as the new `Multihash` and `MultihashRef` in there are mostly working like what I described above. I think a future step is just splitting the encoding functionality either into its own crate or behind a feature flag.

**Comment by vmx** [comment] 2020-02-26 12:48
With the introduction of `multihash:wrap()` the create can do both, hashing and multihash encoding.

If it turns out to be a problem, we could split it into two crates. But for now I'll keep it a single one, hence closing this issue.

**Closed by vmx** 2020-02-26 12:48 UTC
